Add 07-lection5/02-radio solution
js-tasks-ru/htmlcss-20210610_nighthuntersv pull request #15
Opened 2021-06-30 09:43 UTC by NightHunterSV

2021-06-30 09:43 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-30 09:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-30 18:11 UTC, GSemikozov requested changes

2021-06-30 18:11 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    opacity: 0;
при таком варианте скрытия элемент все равно будет иметь свои реальные размеры и при этом пользователь (возможно, даже не подозревая этого) может по-прежнему на него нажать) чтобы этого избежать - как минимум надо задать pointer-events: none, как мы это желали на лекции

2021-06-30 18:11 UTC, GSemikozov commented on 07-lection5/02-radio/radio.css
> +    background-color: var(--grey-2);
тут, пожалуй, важно еще добавить pointer-events: none - пользователь точно не сможет нажать + cursor будет default

2021-06-30 20:10 UTC, NightHunterSV commented on 07-lection5/02-radio/radio.css
> +    background-color: var(--grey-2);
Готово )

2021-06-30 20:14 UTC, NightHunterSV commented on 07-lection5/02-radio/radio.css
> +    opacity: 0;
Абсолютное позиционирование вырвет <input> из flow, и поместит где-то внутри <label> что нас по логике в принципе и устраивает :) Клик в любом месте <label> всё равно включает радиокнопку.
Если же контрол disabled -- то его всё равно не кликнешь.
Допускаю, что в каких-то ситуациях может быть важно: по <input>'у кликнули -- или по <label>, так что изменения внёс :)

2021-07-02 08:10 UTC, GSemikozov approved these changes

2021-07-02 08:10 UTC, merged