Add solution for 03-lection1/01-button
js-tasks-ru/htmlcss-20210610_nighthuntersv pull request #3
Opened 2021-06-21 19:32 UTC by NightHunterSV

2021-06-21 19:32 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-21 19:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-22 12:30 UTC, GSemikozov requested changes

2021-06-22 12:30 UTC, GSemikozov commented on 03-lection1/01-button/button.css
> +    cursor: not-allowed;
для любых состояний disabled лучше прописывать `pointer-events: none` - так мы запретим пользователю нажимать на кнопку, ну и курсор будет по умолчанию `default`

2021-06-22 13:01 UTC, GSemikozov approved these changes

2021-06-22 13:01 UTC, merged